# {{NAME}} — installer generated by the toolkit at {{BASE}}
$ErrorActionPreference = 'Stop'

Write-Host ''
Write-Host '  {{NAME}}' -ForegroundColor Yellow
Write-Host '  {{SUMMARY}}'
Write-Host ''
Write-Host '  from  {{BASE}}'
Write-Host '  into  {{WHERE}}'
Write-Host ''

$py = (Get-Command python -ErrorAction SilentlyContinue) ?? (Get-Command python3 -ErrorAction SilentlyContinue)
if (-not $py) {
  Write-Host '  !! python is not on PATH. Install it from python.org or the Microsoft Store.' -ForegroundColor Red
  exit 1
}
Write-Host ('  python  ' + (& $py.Source -V 2>&1))

$dir = Join-Path $env:TEMP ('minitoolkit-' + [guid]::NewGuid().ToString('N').Substring(0,8))
New-Item -ItemType Directory -Force -Path $dir | Out-Null
try {
  Write-Host ''
  Write-Host '-> fetching the client'
  Invoke-WebRequest '{{BASE}}/minitoolkit.py' -OutFile (Join-Path $dir 'minitoolkit.py')

  Write-Host '-> installing - this writes files and runs nothing from the skill'
  Write-Host ''
  & $py.Source (Join-Path $dir 'minitoolkit.py') skill install '{{NAME}}'{{FLAGS}}

  Write-Host ''
  Write-Host '  done. read it before following it:' -ForegroundColor Green
  Write-Host ('    type ' + (Join-Path $env:USERPROFILE '.claude\skills\{{NAME}}\SKILL.md'))
  Write-Host ''
} finally {
  Remove-Item -Recurse -Force $dir -ErrorAction SilentlyContinue
}
