#!/bin/sh
# {{NAME}} — installer generated by the toolkit at {{BASE}}
set -eu

if [ -t 1 ]; then B=$(printf '\033[1m'); Y=$(printf '\033[1;33m'); G=$(printf '\033[1;32m'); R=$(printf '\033[0m')
else B=''; Y=''; G=''; R=''; fi

printf '\n  %s%s%s\n' "$Y" "{{NAME}}" "$R"
printf '  %s\n' "{{SUMMARY}}"
printf '\n  from  %s\n' "{{BASE}}"
printf '  into  %s\n\n' "{{WHERE}}"

PY=$(command -v python3 2>/dev/null || command -v python 2>/dev/null || true)
if [ -z "$PY" ]; then
  printf '  !! python3 is not on PATH. On Ubuntu:  sudo apt install python3\n\n'
  exit 1
fi
if ! command -v curl >/dev/null 2>&1; then
  printf '  !! curl is not on PATH. On Ubuntu:  sudo apt install curl\n\n'
  exit 1
fi
printf '  python  %s\n' "$("$PY" -V 2>&1)"

DIR=$(mktemp -d)
trap 'rm -rf "$DIR"' EXIT

printf '\n%s->%s fetching the client\n' "$B" "$R"
curl -fsSL "{{BASE}}/minitoolkit.py" -o "$DIR/minitoolkit.py"

printf '%s->%s installing — this writes files and runs nothing from the skill\n\n' "$B" "$R"
"$PY" "$DIR/minitoolkit.py" skill install "{{NAME}}"{{FLAGS}}

printf '\n  %sdone%s. read it before following it:\n' "$G" "$R"
printf '    less ~/.claude/skills/{{NAME}}/SKILL.md\n\n'
